aventure_web/urls.py
from django.urls import path

from . import views

# On ajouter la variable app_name pour indiquer le namespace dans lequel on se trouve
# Voir django_les_portes_sombres/urls.py
app_name = "aventure"

urlpatterns = [
    path("", views.index, name="index"),
    path("selection-hero", views.selection_hero, name="selection"),
    path("intro", views.intro, name="intro"),
]

django_les_portes_sombres/urls.py
from django.contrib import admin
from django.urls import path, include

import aventure_web.views

# Ceci défini le "context root" de l'application
# ex: http://127.0.0.1:8000/admin ouvre l'application d'administration
# http://127.0.0.1:8000/aventure ouvre notre application "aventure_web" (aussi un package python) et prend les configs
# de son fichier urls.py
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', aventure_web.views.index),
    path("aventure/", include(("aventure_web.urls", "aventure_web"), namespace="aventure")),
]

aventure_web/models.py
from django.db import models


# Create your models here.
# Les classes modélisées seront persistées dans une BD (sauf les classes abstraites)
# Voir https://docs.djangoproject.com/en/5.0/topics/db/models/
class Classe(models.Model):
    nom = models.CharField(max_length=20)
    description = models.CharField(max_length=255)
    # Va contenir le path vers l'image de la classe
    path_image = models.CharField(max_length=255)


class Hero(models.Model):
    nom = models.CharField(max_length=50)
    classe = models.ForeignKey(Classe, on_delete=models.CASCADE)

aventure_web/forms.py
from django import forms
from random import choice


# Voir https://docs.djangoproject.com/en/5.0/topics/forms/
class SelectionHeroForm(forms.Form):

    @staticmethod
    def generer_nom():
        return choice(["Ariala", "Helvetico", "Wing Ding"])

    nom_hero = forms.CharField(max_length=50, min_length=1, empty_value=generer_nom(), label="Nom du héro")
    classe_id = forms.IntegerField()

aventure_web/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from aventure_web.models import Classe, Hero
from .forms import SelectionHeroForm


# Create your views here.
def index(request):
    template = loader.get_template("aventure_web/index.html")

    liste_classes = Classe.objects.all()
    # On se construit un dictionnaire qui va contenir le "context" du template (les données que l'on veut utiliser
    # dans le template pour cette "request")
    context = {
        "classes": liste_classes
    }
    return HttpResponse(template.render(context, request))


def selection_hero(request):
    # Créer la form avec les données provenant du request
    form = SelectionHeroForm(request.POST)
    if form.is_valid():
        # Aller chercher l'objet de la Classe sélectionnée à partir de la BD
        classe_hero = Classe.objects.get(id=form.data['classe_id'])

        hero = Hero()
        hero.nom = form.data['nom_hero']
        hero.classe = classe_hero
        # Sauvegarde en BD
        hero.save()
        # Mettre en session la variable nom_hero
        request.session['nom_hero'] = hero.nom
        return HttpResponseRedirect("intro")
    else:
        return index(request)


def intro(request):
    template = loader.get_template("aventure_web/intro.html")
    context = {
        # Exemple d'aller chercher une variable dans la session pour l'assigner à une variable du context
        # Il est possible d'accéder à une variable de session directement dans le template sans la passer par le context
        'nom_hero_ctx': request.session.get('nom_hero'),
    }
    return HttpResponse(template.render(context, request))

aventure_web/templates/aventure_web/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Les Portes Sombres </title>
</head>
<body>
    <form action="{% url 'aventure:selection' %}" method="POST">
        <!-- Ajout d'un CSRF Token -->
        {% csrf_token %}
        <div>Êtes-vous prêt à affronter les portes sombres?</div>
        <table>
            <th>Classe</th>
            <th>Description</th>
            <!-- La liste heros est passé dans la réponse, voir views.py -->
            <th>Sélection</th>
            {% for classe in classes %}
                <tr>
                    <td>{{ classe.nom }}</td>
                    <td>{{ classe.description }}</td>
                    <td><label for="classe">
                        <input type="radio" id="{{ classe.id }}" name="classe_id" value="{{ classe.id }}">
                    </label></td>
                </tr>

            {% endfor %}
        </table>

        <label for="nom_hero">
            Nom du héro:
            <input type="text" name="nom_hero">
        </label>
        <input type="submit" value="Commencer l'aventure!">
    </form>
    <p>

    </p>
</body>
</html>

aventure_web/templates/aventure_web/intro.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!-- Example en allant chercher une variable directement de la session-->
    <title>La croisée des chemins: les aventures de {{ request.session.nom_hero }}</title>
    {% load django_bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body>
    <p>
        <!-- Exemple d'aller chercher une variable passée par le context-->
       <div id="hero-nom">{{ nom_hero_ctx }},</div>vous arrivez près d'une intersection où trois chemins s'offrent à vous.
    </p>
    <p>
        <ul class="list-group">
            <li class="list-group-item">Celui de gauche mène vers un petit village</li>
            <li class="list-group-item">À droite se trouve une caverne dont l'entrée est bloquée</li>
            <li class="list-group-item">Devant, il y a un écriteau au bord du chemin: "Portes Sombres devant. À vos risques et périls!"</li>
        </ul>
    </p>
    <p>
        Que faites-vous?
    </p>
</body>
</html>